"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {Arrow,Footer,Header,Motion,Photo,ProductCard,products} from "./site";
const categories=["All","Grip","Free weights","Racks + benches","Accessories"];
export default function Catalogue(){const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[selected,setSelected]=useState(products[0]);const dialog=useRef<HTMLDialogElement>(null);
useEffect(()=>{const params=new URLSearchParams(window.location.search);const c=params.get("category");if(c&&categories.includes(c))setCategory(c);const p=products.find(p=>p.slug===params.get("product"));if(p){setSelected(p);dialog.current?.showModal()}},[]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{context.registerTool({name:"filter_temper_equipment",description:"Filter the visible TEMPER concept catalogue. Changes only the visible category and search text.",inputSchema:{type:"object",properties:{category:{type:"string",enum:categories},query:{type:"string",maxLength:100}},required:["category"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const value=input as {category:string,query?:string};if(!value||!categories.includes(value.category)||typeof(value.query??"")!=="string"||(value.query?.length??0)>100)throw new Error("Invalid catalogue filter");setCategory(value.category);setQuery(value.query??"");await new Promise(requestAnimationFrame);return {category:value.category,products:products.filter(p=>(value.category==="All"||p.category===value.category)&&`${p.name} ${p.type}`.toLowerCase().includes((value.query??"").toLowerCase())).map(p=>({name:p.name,availability:"To be confirmed"}))}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[]);
const filtered=products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.type}`.toLowerCase().includes(query.toLowerCase()));
return <><Header solid/><main id="main" className="catalogue shell light"><p className="label muted">TEMPER / THE CONCEPT COLLECTION</p><h1>EQUIPMENT</h1><div className="catalogue-intro"><p>Built around training.</p><span className="label muted">AVAILABLE AT LAUNCH / SPECIFICATIONS TO BE CONFIRMED</span></div><div className="catalogue-controls"><div className="filters" role="group" aria-label="Equipment category">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c.toUpperCase()}</button>)}</div><label className="catalogue-search"><span className="sr-only">Search catalogue</span><input type="search" placeholder="Search equipment" value={query} onChange={e=>setQuery(e.target.value)}/><span aria-hidden="true">⌕</span></label></div><div className="results-count label" aria-live="polite">{filtered.length?`${String(filtered.length).padStart(2,"0")} CONCEPTS`:"COLLECTION IN DEVELOPMENT"}</div><div className="product-grid">{filtered.map(p=><div key={p.slug} className={`catalogue-card-wrap ${category==="All"&&!query?p.className:""}`} onClick={e=>{if(p.slug!=="hex-20"){e.preventDefault();setSelected(p);dialog.current?.showModal()}}}><ProductCard product={p} compact/></div>)}</div>{!filtered.length&&<div className="catalogue-empty"><h2>{query?"NOT IN THE COLLECTION.":"THE NEXT CHAPTER."}</h2><p>{query?"Try another search or browse all equipment.":`${category} are part of the planned TEMPER collection. Product details will be available at launch.`}</p><button className="text-link" onClick={()=>{setCategory("All");setQuery("")}}>VIEW ALL EQUIPMENT<Arrow/></button></div>}<p className="prototype-note">Prototype imagery. Final products and specifications subject to manufacturing partner agreements.</p></main><Footer/><Motion/><dialog className="dialog product-dialog" ref={dialog} aria-labelledby="concept-name"><div className="dialog-head"><span className="label">{selected.code} / CONCEPT EQUIPMENT</span><button className="icon-button" aria-label="Close product" onClick={()=>dialog.current?.close()}><span className="cross">×</span></button></div><Photo name={selected.image} alt={`Unbranded ${selected.type} concept`}/><h2 id="concept-name">{selected.name}</h2><p>{selected.type}</p><dl><div><dt>Specifications</dt><dd>To be confirmed</dd></div><div><dt>Pricing & availability</dt><dd>Available at launch</dd></div></dl><Link href="/request-quote" className="button">REGISTER YOUR INTEREST<Arrow/></Link><p className="prototype-note">Prototype product. Final specifications are subject to manufacturing partner agreements.</p></dialog></>}
