"use client";
import Link from "next/link";
import {Arrow,Button,Footer,Header,Motion,Photo,ProductCard,SectionTop,products} from "./site";
import Hero from "./hero";
import {Categories,Construction,Journal,Process} from "./editorial";
export default function Home(){return <><Header/><main id="main"><Hero/>
<section id="manifesto" className="manifesto shell light"><SectionTop index="01" title="THE INTENT" end="PROGRESS IS THE POINT"/><div className="manifesto-grid"><h2 className="reveal">TRAINING IS<br/>MEASURED IN<br/><span className="outline-word">PROGRESS.</span></h2><div className="manifesto-copy reveal"><p>Another rep.<br/>Another kilo.<br/>Another session.</p><span>Equipment should keep up.</span><div className="rep-counter" aria-hidden="true"><span>01</span><span>02</span><span>03</span></div></div></div></section>
<section id="equipment" className="exhibition shell light"><SectionTop index="02" title="SELECTED EQUIPMENT" end="001 — 004"/><div className="exhibition-intro reveal"><h2>LESS NOISE.<br/>MORE WEIGHT.</h2><p>A considered collection.<br/>Every object has a purpose.<br/>Every detail earns its place.</p></div><div className="product-grid">{products.map(p=><ProductCard key={p.slug} product={p}/>)}</div><div className="exhibition-bottom"><p>Concept collection. Product names and imagery are illustrative. Final specifications and availability to be confirmed.</p><Link href="/equipment" className="text-link">EXPLORE THE COLLECTION<Arrow/></Link></div></section>
<section className="feature-track" aria-label="HEX 20 product story"><div className="feature shell"><div className="feature-label label"><span>TEMPER / FREE WEIGHTS / 001</span><span>FORM FOLLOWS FUNCTION.</span></div><h2>MADE TO<br/>BE DROPPED.</h2><Photo className="feature-image" name="dumbbell" alt="Hex dumbbell concept, showing its rubber heads and steel handle"/><div className="feature-number"><strong>20<small>KG</small><sup>*</sup></strong><span className="label">CONCEPT WEIGHT</span></div><div className="annotation label">KNURLED HANDLE<span>TACTILE BY DESIGN / CONCEPT</span></div><div className="feature-footer"><p>*Prototype value. Commercial construction, final weight, materials and performance specifications to be confirmed.</p><Link className="text-link" href="/equipment/hex-20">MEET HEX 20<Arrow/></Link></div><div className="story-progress" aria-hidden="true"><span/></div></div></section>
<section className="macro shell"><Photo name="knurling" alt="Extreme close-up of diamond knurling on a steel handle"/><span className="label">03 / IN THE DETAILS</span><div className="macro-copy"><h2>THE DIFFERENCE<br/>IS IN WHAT<br/>YOU TOUCH.</h2><p>The first point of contact. The last thing you should have to think about. Grip is where the work begins.</p></div></section>
<Categories/><section id="commercial" className="commercial shell light"><SectionTop index="05" title="TEMPER / COMMERCIAL" end="A PLACE TO GET STRONGER"/><div className="commercial-head"><h2 className="reveal">BUILD A GYM<br/>WORTH<br/>TRAINING IN.</h2><div className="commercial-copy reveal"><p>Commercial strength equipment for gyms, studios and serious training facilities.</p><Link className="text-link" href="/for-gyms">START YOUR PROJECT<Arrow/></Link></div></div><Link href="/for-gyms" className="gym-image"><Photo name="gym" alt="Concept commercial strength facility with power racks, benches and industrial windows"/><div className="image-caption label"><span>SPACE FOR SERIOUS TRAINING.</span><span>CONCEPT ENVIRONMENT / 2026</span></div></Link><div className="facility-types" aria-label="Facility types">{["COMMERCIAL GYM","STRENGTH STUDIO","RESIDENTIAL","CORPORATE","HOTEL","HOME"].map((x,i)=><Link key={x} href={`/request-quote?facility=${encodeURIComponent(x)}`}><span>0{i+1}</span>{x}</Link>)}</div></section>
<Process/><Construction/><section id="about" className="identity shell"><h2 className="reveal"><span className="faded">SOME PEOPLE<br/>COUNT WORKOUTS.</span><br/>YOU COUNT<br/>KILOS.</h2><div className="identity-bottom"><p>Equipment for people who train.</p><span className="cross" aria-hidden="true">+</span></div></section>
<Journal/><section className="final-cta shell light"><SectionTop index="09" title="THE NEXT REP STARTS HERE" end="YOUR MOVE"/><h2 className="reveal">WHAT ARE<br/>YOU BUILDING?</h2><div className="cta-choices"><Link className="text-link" href="/equipment">MY TRAINING<Arrow/></Link><Link className="text-link" href="/request-quote">MY GYM<Arrow/></Link></div></section></main><Footer/><Motion/></>}
