"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {Arrow,Header} from "./site";
const facilities=["COMMERCIAL GYM","STRENGTH STUDIO","RESIDENTIAL","CORPORATE","HOTEL","HOME"];
const equipment=["Free weights","Racks + benches","Grip","Accessories","Complete setup","Not sure yet"];
type Brief={facility:string,description:string,city:string,area:string,budget:string,equipment:string[],requirements:string,name:string,phone:string,email:string};
const blank:Brief={facility:"",description:"",city:"",area:"",budget:"",equipment:[],requirements:"",name:"",phone:"",email:""};
export default function Quote(){const [step,setStep]=useState(0),[brief,setBrief]=useState<Brief>(blank),[done,setDone]=useState(false),[stored,setStored]=useState(false),[error,setError]=useState("");const title=useRef<HTMLHeadingElement>(null);const form=useRef<HTMLFormElement>(null);useEffect(()=>{const facility=new URLSearchParams(window.location.search).get("facility");if(facility&&facilities.includes(facility))setBrief(b=>({...b,facility}))},[]);const field=(key:keyof Brief,value:string)=>setBrief(b=>({...b,[key]:value}));function next(e:React.FormEvent){e.preventDefault();if(step===2&&!brief.equipment.length){setError("Select at least one option, or choose ‘Not sure yet’.");return}setError("");if(step<3){setStep(step+1);requestAnimationFrame(()=>title.current?.focus())}else{try{localStorage.setItem("temper-project-brief",JSON.stringify(brief));setStored(true)}catch{setStored(false)}setDone(true);requestAnimationFrame(()=>title.current?.focus())}}function toggle(value:string){setBrief(b=>({...b,equipment:b.equipment.includes(value)?b.equipment.filter(v=>v!==value):[...b.equipment,value]}));setError("")}
return <><Header solid/><main id="main" className="quote-page light shell"><aside className="quote-aside"><Link href="/for-gyms" className="label">← BACK TO FOR GYMS</Link><h1>LET’S BUILD<br/>SOMETHING<br/>SERIOUS.</h1><p>Your space. Your training.<br/>A considered place to start.</p><ol className="quote-steps">{["YOUR PROJECT","YOUR SPACE","YOUR EQUIPMENT","YOUR DETAILS"].map((s,i)=><li key={s} className={i===step?"active":i<step?"complete":""} aria-current={i===step?"step":undefined}><span>0{i+1}</span>{s}{i<step&&<span className="step-check">✓</span>}</li>)}</ol><p className="prototype-note">Pre-launch prototype.<br/>This form saves only to your browser. No enquiry is sent and no quote is issued.</p></aside><section className="quote-form-section">{done?<div className="quote-success"><span className="success-mark">↗</span><p className="label">PROJECT BRIEF / COMPLETE</p><h2 ref={title} tabIndex={-1}>{stored?"YOUR NEXT CHAPTER.\nSAVED.":"YOUR BRIEF.\nREADY."}</h2><p role="status">{stored?"Your project brief has been saved on this device. Nothing has been sent to TEMPER; this is a demonstration of the quotation experience.":"Your brief is ready for this preview. Browser storage is unavailable, so it has not been saved or sent."}</p><dl className="brief-summary"><div><dt>Project</dt><dd>{brief.facility}</dd></div><div><dt>Location</dt><dd>{brief.city}</dd></div><div><dt>Equipment</dt><dd>{brief.equipment.join(", ")}</dd></div><div><dt>Contact</dt><dd>{brief.name}<br/>{brief.email}</dd></div></dl><button className="text-link" onClick={()=>{setDone(false);setStep(0)}}>EDIT MY BRIEF<Arrow/></button><Link className="text-link" href="/">BACK TO TEMPER<Arrow/></Link></div>:<><div className="quote-step-label label"><span>STEP 0{step+1}</span><span>0{step+1} / 04</span></div><div className="quote-progress"><span style={{width:`${(step+1)*25}%`}}/></div><h2 ref={title} tabIndex={-1}>{["YOUR PROJECT.","YOUR SPACE.","YOUR EQUIPMENT.","YOUR DETAILS."][step]}</h2><form ref={form} onSubmit={next}>
{step===0&&<><fieldset><legend>What kind of space are you building?</legend><div className="choice-grid">{facilities.map(f=><label key={f} className={`choice ${brief.facility===f?"selected":""}`}><input type="radio" name="facility" required value={f} checked={brief.facility===f} onChange={()=>field("facility",f)}/><span>{f}</span><span className="choice-indicator">{brief.facility===f?"↗":"+"}</span></label>)}</div></fieldset><label className="form-field">Tell us about your project <span className="optional">(optional)</span><textarea value={brief.description} onChange={e=>field("description",e.target.value)} placeholder="The training, the people, the idea behind your space…" rows={3} maxLength={2000}/></label></>}
{step===1&&<><label className="form-field">City<input required autoComplete="address-level2" value={brief.city} onChange={e=>field("city",e.target.value)} placeholder="e.g. Vadodara" maxLength={100}/></label><label className="form-field">Approximate floor area<select required value={brief.area} onChange={e=>field("area",e.target.value)}><option value="" disabled>Select your space</option>{["Under 500 sq ft","500–1,000 sq ft","1,000–2,500 sq ft","2,500–5,000 sq ft","5,000+ sq ft","To be confirmed"].map(a=><option key={a}>{a}</option>)}</select></label><label className="form-field">Approximate budget<select required value={brief.budget} onChange={e=>field("budget",e.target.value)}><option value="" disabled>Select a budget range</option>{["Under ₹5 lakh","₹5–10 lakh","₹10–25 lakh","₹25 lakh+","Not decided"].map(a=><option key={a}>{a}</option>)}</select></label></>}
{step===2&&<><fieldset aria-describedby={error?"equipment-error":undefined}><legend>What belongs on your training floor?</legend><p className="field-help">Choose all that apply.</p><div className="choice-grid">{equipment.map(f=><label key={f} className={`choice ${brief.equipment.includes(f)?"selected":""}`}><input type="checkbox" checked={brief.equipment.includes(f)} onChange={()=>toggle(f)}/><span>{f.toUpperCase()}</span><span className="choice-indicator">{brief.equipment.includes(f)?"✓":"+"}</span></label>)}</div></fieldset>{error&&<p id="equipment-error" className="form-error" role="alert">{error}</p>}<label className="form-field">Equipment requirements <span className="optional">(optional)</span><textarea value={brief.requirements} onChange={e=>field("requirements",e.target.value)} placeholder="Specific equipment, quantities, or anything else you have in mind." rows={3} maxLength={2000}/></label></>}
{step===3&&<><p className="field-help details-help">A few details to complete your project brief.</p><label className="form-field">Name<input required autoComplete="name" value={brief.name} onChange={e=>field("name",e.target.value)} placeholder="Your full name" maxLength={100}/></label><label className="form-field">Phone<input required type="tel" autoComplete="tel" value={brief.phone} onChange={e=>field("phone",e.target.value)} placeholder="+91" pattern="[+0-9 ]{7,20}" title="Enter 7–20 characters using digits, spaces and an optional + prefix."/></label><label className="form-field">Email<input required type="email" autoComplete="email" value={brief.email} onChange={e=>field("email",e.target.value)} placeholder="you@example.com" maxLength={200}/></label><p className="prototype-note">By saving, you keep this brief on this device only. No mailing list subscription or external submission occurs.</p></>}
<div className="form-actions">{step>0?<button type="button" className="back-button" onClick={()=>{setStep(step-1);setError("");requestAnimationFrame(()=>title.current?.focus())}}>← BACK</button>:<span className="label muted">TAKE YOUR TIME.</span>}<button type="submit" className="button">{step===3?"SAVE PROJECT BRIEF":"CONTINUE"}<Arrow/></button></div></form></>}</section></main></>}
