"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";

export const products = [
 {slug:"hex-20",name:"HEX 20",type:"Commercial dumbbell",category:"Free weights",image:"dumbbell",code:"001",className:"hex"},
 {slug:"grip-150",name:"GRIP 150",type:"Torsion spring gripper",category:"Grip",image:"gripper",code:"002",className:"grip"},
 {slug:"bar-20",name:"BAR 20",type:"Olympic barbell",category:"Free weights",image:"barbell",code:"003",className:"bar"},
 {slug:"plate-20",name:"PLATE 20",type:"Olympic weight plate",category:"Free weights",image:"plate",code:"004",className:"plate"},
];
export type Product=typeof products[number];
export function Arrow(){return <svg className="arrow" width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" strokeWidth="1.4"/></svg>}
export function Photo({name,alt,className="",priority=false}:{name:string,alt:string,className?:string,priority?:boolean}){return <img className={className} src={`/images/${name}.webp`} srcSet={`/images/${name}-small.webp 640w, /images/${name}.webp 1536w`} sizes="(max-width:767px) 100vw, 90vw" alt={alt} loading={priority?"eager":"lazy"} fetchPriority={priority?"high":"auto"} decoding="async" width="1536" height="1024"/>}
export function Button({href,children,outline=false}:{href:string,children:React.ReactNode,outline?:boolean}){return <Link href={href} className={`button${outline?" outline":""}`}>{children}<Arrow/></Link>}
export function SectionTop({index,title,end}:{index:string,title:string,end?:string}){return <div className="section-top label"><div className="index-label"><span>{index} /</span><span>{title}</span></div><span>{end||"TEMPER"}</span></div>}
export function ProductCard({product,compact=false}:{product:Product,compact?:boolean}){return <Link className={`product-card object-card ${product.className} ${compact?"compact":""}`} href={product.slug==="hex-20"?"/equipment/hex-20":`/equipment?product=${product.slug}`} aria-label={`View ${product.name}, ${product.type}`}><div className="product-art"><div className="art-label label"><span>{product.code} / THE OBJECT</span><span>CONCEPT</span></div><span className="object-word" aria-hidden="true">{product.name.split(" ")[0]}</span><Photo name={product.image} alt={`Unbranded ${product.type.toLowerCase()} concept, photographed as an engineered object`}/><span className="art-mark" aria-hidden="true">+</span><span className="view-object">EXPLORE THE OBJECT <Arrow/></span></div><div className="card-bottom"><div><h3>{product.name}</h3><p>{product.type}</p></div><span className="label">{product.category}</span></div></Link>}

export function Header({solid=false}:{solid?:boolean}){
 const [scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false),[query,setQuery]=useState("");const dialog=useRef<HTMLDialogElement>(null);const search=useRef<HTMLInputElement>(null);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>30);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[]);
 useEffect(()=>{if(!menu)return;const original=document.body.style.overflow;document.body.style.overflow="hidden";const content=Array.from(document.querySelectorAll<HTMLElement>("main,footer"));content.forEach(el=>el.inert=true);const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);document.querySelector<HTMLButtonElement>(".menu-toggle")?.focus()}if(e.key==="Tab"){const items=Array.from(document.querySelectorAll<HTMLElement>(".menu-toggle,#mobile-menu a,#mobile-menu button"));const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=original;content.forEach(el=>el.inert=false);window.removeEventListener("keydown",close)}},[menu]);
 function openSearch(){setQuery("");dialog.current?.showModal();requestAnimationFrame(()=>search.current?.focus())}
 const results=products.filter(p=>`${p.name} ${p.type} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <><a className="skip-link" href="#main">Skip to content</a><header className={`header ${scrolled?"scrolled":""} ${solid||menu?"solid":""}`}><Link href="/" className="wordmark" aria-label="Temper home">TEMPER<sup>™</sup></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/equipment">Equipment</Link><Link href="/for-gyms">For Gyms</Link><Link href="/#journal">Journal</Link><Link href="/#about">About</Link></nav><div className="header-actions"><button className="icon-button" onClick={openSearch} aria-label="Search equipment"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" strokeWidth="1.5"/><path d="m16 16 4.5 4.5" stroke="currentColor" strokeWidth="1.5"/></svg></button><Link href="/request-quote" className="quote-link">GET A QUOTE<Arrow/></Link></div><button className="menu-toggle" aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?"CLOSE":"MENU"}<span className="cross">{menu?"×":"+"}</span></button></header>{menu&&<nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation">{[["Equipment","/equipment"],["For Gyms","/for-gyms"],["Journal","/#journal"],["About","/#about"],["Get a quote","/request-quote"]].map(([title,url])=><Link key={title} href={url} onClick={()=>setMenu(false)}>{title}<Arrow/></Link>)}<button className="text-link" onClick={()=>{setMenu(false);openSearch()}}>SEARCH EQUIPMENT<Arrow/></button><p className="label">VADODARA, INDIA<br/>PRE-LAUNCH / 2026</p></nav>}<dialog ref={dialog} className="dialog" aria-labelledby="search-title" onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}><div className="dialog-head"><h2 id="search-title">Find your equipment.</h2><button className="icon-button" aria-label="Close search" onClick={()=>dialog.current?.close()}><span className="cross">×</span></button></div><label className="label" htmlFor="equipment-search">SEARCH THE CONCEPT COLLECTION</label><input ref={search} id="equipment-search" className="search-input" placeholder="Try dumbbell, grip, or barbell" value={query} onChange={e=>setQuery(e.target.value)} type="search"/><div className="search-results" aria-live="polite">{results.map(p=><Link key={p.slug} className="search-result" href={p.slug==="hex-20"?"/equipment/hex-20":`/equipment?product=${p.slug}`} onClick={()=>dialog.current?.close()}><Photo name={p.image} alt=""/><div><strong>{p.name}</strong><p>{p.type}</p></div><Arrow/></Link>)}{!results.length&&<p className="empty-state">No equipment found. Try “grip”, “barbell” or “free weights”.</p>}</div></dialog></>;
}
export function Footer(){return <footer className="footer shell"><div className="footer-top"><p className="footer-intro">Equipment for people<br/>who train.</p><nav className="footer-nav" aria-label="Footer navigation"><Link href="/equipment">Equipment</Link><Link href="/#about">About</Link><Link href="/for-gyms">For Gyms</Link><Link href="/request-quote">Contact</Link><Link href="/#journal">Journal</Link><Link href="/request-quote">Get a quote</Link></nav><div className="footer-location"><p className="label">BASED IN INDIA</p><p>Vadodara<br/>Gujarat, India</p></div></div><Link href="/" aria-label="Temper home"><div className="footer-wordmark" aria-hidden="true">TEMPER</div></Link><div className="footer-bottom"><span className="label">PRE-LAUNCH PROTOTYPE / 2026</span><p>Prototype imagery. Final products and specifications subject to manufacturing partner agreements.</p><a className="back-top" href="#main">BACK TO TOP<Arrow/></a></div></footer>}
export function Motion(){useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;document.documentElement.classList.add("motion-ready");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));let frame=0;const update=()=>{frame=0;const hero=document.querySelector<HTMLElement>(".hero-object");if(hero&&window.scrollY<1300)hero.style.setProperty("--drift", `${Math.min(window.scrollY*.12,100)}px`);const story=document.querySelector<HTMLElement>(".feature-track");if(story){const rect=story.getBoundingClientRect();const progress=Math.max(0,Math.min(1,-rect.top/(rect.height-window.innerHeight)));const line=story.querySelector<HTMLElement>(".story-progress span");if(line)line.style.width=`${progress*100}%`}};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener("scroll",scroll,{passive:true});update();return()=>{observer.disconnect();window.removeEventListener("scroll",scroll);cancelAnimationFrame(frame);document.documentElement.classList.remove("motion-ready")}},[]);return null}
